### ISSUE TITLE
Issue when starting bot

### ISSUE THREAD

**Issue by OfficerRicer** [dlchamp/CustomDMRoleMessages#2]
![image](https://user-images.githubusercontent.com/52828546/217124514-9fa985df-03d3-4347-a47b-889924f853c9.png)

**Comment by dlchamp** [comment]
Can you confirm the disnake version you are using?

**Comment by OfficerRicer** [comment]
2.4.0

**Comment by OfficerRicer** [comment]
![image](https://user-images.githubusercontent.com/52828546/217613514-b66e3060-b617-4815-9840-f3e7e8694700.png)
This might have something to do with it

**Comment by dlchamp** [comment]
This project is currently not maintained.   I have plans to rewrite and update it at some point, but it's not feasible at the current moment.
